apiVersion: apps/v1
kind: Service
metadata:
  name: notesapp-service
  namespace: myapp
  labels:
    app: notesapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: notesapp